In [22]:
import mne
import random
import pandas as pd
from pathlib import Path

In [24]:
raw = mne.io.read_raw(selected['path'])
annotations = mne.read_annotations(selected['evt_path'])
raw.set_annotations(annotations)

events, event_id = mne.events_from_annotations(raw)
event_id_inv = {v: k for k, v in event_id.items()}
events, event_id, event_id_inv

Extracting EDF parameters from D:\脑机接口专项\P300(3X3)\5-10\19000089\test_data\data.bdf...
BDF file detected
Setting channel info structure...
Creating raw.info structure...
Used Annotations descriptions: ['1', '101', '102', '103', '104', '105', '106', '107', '108', '109', '2', '200', '241', '242', '243', '250', '251', '3', '4', '5', '6', '7', '8', '9']

(array([[ 25674,      0,     16],
        [ 60727,      0,     14],
        [ 80135,      0,      4],
        ...,
        [481875,      0,     13],
        [483242,      0,     15],
        [488388,      0,     17]]),
 {'1': 1,
  '101': 2,
  '102': 3,
  '103': 4,
  '104': 5,
  '105': 6,
  '106': 7,
  '107': 8,
  '108': 9,
  '109': 10,
  '2': 11,
  '200': 12,
  '241': 13,
  '242': 14,
  '243': 15,
  '250': 16,
  '251': 17,
  '3': 18,
  '4': 19,
  '5': 20,
  '6': 21,
  '7': 22,
  '8': 23,
  '9': 24},
 {1: '1',
  2: '101',
  3: '102',
  4: '103',
  5: '104',
  6: '105',
  7: '106',
  8: '107',
  9: '108',
  10: '109',
  11: '2',
  12: '200',
  13: '241',
  14: '242',
  15: '243',
  16: '250',
  17: '251',
  18: '3',
  19: '4',
  20: '5',
  21: '6',
  22: '7',
  23: '8',
  24: '9'})

In [23]:
found_files = pd.read_pickle('../cache/found_files')
check_results = pd.read_pickle('../cache/check_results')

df = pd.merge(check_results, found_files, on='path')
df = df[df['status'] != 'failed']
# df = df[df['protocol'] == 'P300(二项式)']
df = df[df['protocol'] == 'P300(3X3)']
df

selected = df.loc[random.choice(df.index)]
selected

path          D:\脑机接口专项\P300(3X3)\5-10\19000089\test_data\da...
status                                                   passed
checks        {'ch_names': ['Fpz', 'Fp1', 'Fp2', 'AF3', 'AF4...
suspects          {'channels': [], 'sfreq': [], 'n_events': []}
evt_path      D:\脑机接口专项\P300(3X3)\5-10\19000089\test_data\ev...
short_name           P300(3X3)/5-10/19000089/test_data/data.bdf
protocol                                              P300(3X3)
format                                                     .bdf
Name: 156, dtype: object

In [25]:
real_events = [event_id_inv[e] for e in events[:, -1]]
real_events

['250',
 '242',
 '103',
 '2',
 '6',
 '1',
 '4',
 '3',
 '5',
 '9',
 '8',
 '7',
 '200',
 '7',
 '4',
 '6',
 '3',
 '8',
 '9',
 '5',
 '2',
 '1',
 '200',
 '241',
 '106',
 '5',
 '2',
 '6',
 '3',
 '8',
 '4',
 '7',
 '1',
 '9',
 '200',
 '8',
 '7',
 '5',
 '1',
 '3',
 '4',
 '9',
 '2',
 '6',
 '200',
 '241',
 '103',
 '8',
 '1',
 '4',
 '2',
 '5',
 '9',
 '3',
 '6',
 '7',
 '200',
 '6',
 '3',
 '2',
 '7',
 '1',
 '9',
 '8',
 '4',
 '5',
 '200',
 '241',
 '102',
 '4',
 '8',
 '2',
 '7',
 '1',
 '9',
 '5',
 '3',
 '6',
 '200',
 '6',
 '1',
 '3',
 '9',
 '8',
 '4',
 '7',
 '2',
 '5',
 '200',
 '241',
 '101',
 '7',
 '5',
 '1',
 '4',
 '6',
 '3',
 '9',
 '2',
 '8',
 '200',
 '9',
 '7',
 '3',
 '5',
 '4',
 '6',
 '2',
 '8',
 '1',
 '200',
 '241',
 '107',
 '6',
 '7',
 '8',
 '5',
 '9',
 '4',
 '1',
 '3',
 '2',
 '200',
 '7',
 '8',
 '5',
 '4',
 '2',
 '9',
 '1',
 '6',
 '3',
 '200',
 '241',
 '105',
 '1',
 '2',
 '9',
 '5',
 '8',
 '4',
 '6',
 '7',
 '3',
 '200',
 '2',
 '8',
 '4',
 '6',
 '7',
 '5',
 '3',
 '9',
 '1',
 '200',
 '241',
 '243',
 '242',
 '104',
 '9',
 '4',
 '2',
 '3',
 '8',
 '1',
 '6',
 '5',
 '7',
 '200',
 '2',
 '3',
 '9',
 '1',
 '4',
 '8',
 '7',
 '6',
 '5',
 '200',
 '241',
 '104',
 '1',
 '6',
 '5',
 '9',
 '7',
 '8',
 '4',
 '2',
 '3',
 '200',
 '3',
 '8',
 '7',
 '5',
 '9',
 '2',
 '1',
 '6',
 '4',
 '200',
 '241',
 '104',
 '5',
 '8',
 '7',
 '4',
 '3',
 '6',
 '9',
 '2',
 '1',
 '200',
 '6',
 '7',
 '2',
 '9',
 '4',
 '3',
 '1',
 '8',
 '5',
 '200',
 '241',
 '107',
 '6',
 '1',
 '2',
 '7',
 '3',
 '9',
 '8',
 '4',
 '5',
 '200',
 '3',
 '4',
 '9',
 '2',
 '8',
 '6',
 '1',
 '7',
 '5',
 '200',
 '241',
 '109',
 '2',
 '1',
 '6',
 '9',
 '8',
 '7',
 '5',
 '3',
 '4',
 '200',
 '3',
 '6',
 '7',
 '2',
 '1',
 '5',
 '9',
 '4',
 '8',
 '200',
 '241',
 '109',
 '9',
 '2',
 '7',
 '6',
 '3',
 '5',
 '1',
 '4',
 '8',
 '200',
 '2',
 '5',
 '4',
 '6',
 '7',
 '9',
 '3',
 '8',
 '1',
 '200',
 '241',
 '106',
 '3',
 '9',
 '7',
 '4',
 '6',
 '1',
 '8',
 '5',
 '2',
 '200',
 '1',
 '5',
 '9',
 '3',
 '7',
 '4',
 '6',
 '8',
 '2',
 '200',
 '241',
 '105',
 '3',
 '8',
 '9',
 '5',
 '6',
 '7',
 '1',
 '2',
 '4',
 '200',
 '3',
 '8',
 '5',
 '9',
 '4',
 '1',
 '2',
 '6',
 '7',
 '200',
 '241',
 '243',
 '242',
 '102',
 '7',
 '4',
 '2',
 '8',
 '3',
 '9',
 '6',
 '1',
 '5',
 '200',
 '9',
 '2',
 '4',
 '1',
 '5',
 '8',
 '3',
 '6',
 '7',
 '200',
 '241',
 '103',
 '7',
 '8',
 '4',
 '1',
 '2',
 '6',
 '9',
 '5',
 '3',
 '200',
 '1',
 '5',
 '4',
 '9',
 '3',
 '6',
 '8',
 '7',
 '2',
 '200',
 '241',
 '109',
 '2',
 '5',
 '3',
 '7',
 '8',
 '6',
 '1',
 '9',
 '4',
 '200',
 '8',
 '6',
 '9',
 '7',
 '2',
 '4',
 '3',
 '5',
 '1',
 '200',
 '241',
 '108',
 '9',
 '4',
 '8',
 '3',
 '6',
 '5',
 '7',
 '2',
 '1',
 '200',
 '9',
 '4',
 '6',
 '7',
 '3',
 '5',
 '8',
 '1',
 '2',
 '200',
 '3',
 '7',
 '2',
 '8',
 '4',
 '1',
 '6',
 '5',
 '9',
 '200',
 '241',
 '108',
 '6',
 '8',
 '7',
 '3',
 '2',
 '5',
 '1',
 '4',
 '9',
 '200',
 '2',
 '3',
 '6',
 '5',
 '8',
 '1',
 '4',
 '7',
 '9',
 '200',
 '241',
 '107',
 '6',
 '2',
 '9',
 '7',
 '8',
 '3',
 '1',
 '4',
 '5',
 '200',
 '4',
 '7',
 '9',
 '6',
 '1',
 '3',
 '8',
 '2',
 '5',
 '200',
 '241',
 '105',
 '2',
 '7',
 '6',
 '4',
 '1',
 '5',
 '3',
 '9',
 '8',
 '200',
 '4',
 '7',
 '2',
 '1',
 '9',
 '6',
 '3',
 '5',
 '8',
 '200',
 '5',
 '3',
 '7',
 '8',
 '4',
 '6',
 '2',
 '9',
 '1',
 '200',
 '1',
 '2',
 '9',
 '4',
 '5',
 '3',
 '7',
 '8',
 '6',
 '200',
 '241',
 '243',
 '242',
 '101',
 '9',
 '7',
 '8',
 '5',
 '3',
 '4',
 '6',
 '2',
 '1',
 '200',
 '5',
 '9',
 '6',
 '7',
 '8',
 '1',
 '3',
 '2',
 '4',
 '200',
 '241',
 '101',
 '5',
 '1',
 '8',
 '7',
 '4',
 '6',
 '3',
 '9',
 '2',
 '200',
 '8',
 '3',
 '5',
 '1',
 '9',
 '4',
 '7',
 '2',
 '6',
 '200',
 '241',
 '101',
 '2',
 '9',
 '8',
 '3',
 '4',
 '5',
 '1',
 '6',
 '7',
 '200',
 '6',
 '8',
 '9',
 '1',
 '2',
 '5',
 '4',
 '7',
 '3',
 '200',
 '241',
 '101',
 '5',
 '8',
 '3',
 '4',
 '9',
 '7',
 '1',
 '2',
 '6',
 '200',
 '8',
 '4',
 '5',
 '2',
 '1',
 '3',
 '6',
 '7',
 '9',
 '200',
 '241',
 '101',
 '3',
 '9',
 '8',
 '5',
 '7',
 '1',
 '2',
 '6',
 '4',
 '200',
 '6',
 '7',
 '1',
 '5',
 '4',
 '2',
 '3',
 '9',
 '8',
 '200',
 '241',
 '101',
 '3',
 '4',
 '8',
 '6',
 '2',
 '1',
 '7',
 '5',
 '9',
 '200',
 '7',
 '8',
 '2',
 '1',
 '3',
 '5',
 '6',
 '4',
 '9',
 '200',
 '241',
 '243',
 '251']

In [26]:
events_df = pd.DataFrame(events, columns=['time', 'duration', 'code'])
events_df['label'] = 0
events_df['label'] = events_df['label'].map(lambda e: random.randint(0, 1))
events_df.to_csv('label.csv')
events_df

       time  duration  code  label
0     25674         0    16      1
1     60727         0    14      1
2     80135         0     4      1
3     80159         0    11      0
4     80405         0    21      1
..      ...       ...   ...    ...
651  480752         0    24      0
652  481008         0    12      0
653  481875         0    13      0
654  483242         0    15      1
655  488388         0    17      0

[656 rows x 4 columns]